spring.application.name=travelPlanner-rest

spring.security.user.name=rahat
spring.security.user.password=1234

spring.mongodb.uri=mongodb+srv://codingwithrahat_db_user:7dYesVfWU6Cc6lJ5@cluster0.znxmaca.mongodb.net/travelPlan?appName=Cluster0


